### ISSUE TITLE
Doesnt work?

### ISSUE THREAD

**Issue by bradennapier** [ldez/atom-grammar-live-reload#1]
As far as I can tell this does not do anything anymore.

trying to edit language-tcltk - i do anything and nothing changes (in developer mode)

**Comment by ldez** [comment]
could you provide more information?

**Comment by bradennapier** [comment]
I'm pretty sure this just straight up doesn't work in the latest versions.

I am in developer mode, I opened the langauge-tclk in developer mode.  I change it, nothing changes.  My tcl file will not reload its style no matter what I do.  tried every other language package to make srue none of them seem to do anything at all when i the .cson files

**Comment by ldez** [comment]
Do you have some logs?

**Comment by ldez** [comment]
I confirm the feature is broken due to Atom changes.

**Comment by ldez** [comment]
@bradennapier I have fixed the problem 🎉 . Update the package 😃

**Comment by bradennapier** [comment]
Awesome!  Although it isnt working for me :( 

I believe I've done everythingp roperly. is it compatible with cson files?! 

Thanks for working on this! Literally cant wait for this to work - developing grammar is terrible without i!

**Comment by bradennapier** [comment]
Hm no i see you use the cson as well -- hmm wonder why it no work for me :(?

Do I have to be in dev mode on both ?  does the file i am testing the syntax on need to be inside of the package folder or something?>

**Comment by ldez** [comment]
You need to open in only one Atom (in dev mode): the language package and your testing files.

**Comment by bradennapier** [comment]
Yeah that is what i have right now.

**Comment by bradennapier** [comment]
![image](https://user-images.githubusercontent.com/15365418/28218090-4debe942-686c-11e7-9e2a-ec96fd94a175.png)

So i changed the proc-args-braced to punctuation.definition.variable.tcl which makes it red but it has not changed.  

Should it reload automatically as soon as I save or is there a command i have to run?

**Comment by ldez** [comment]
could you give me your sample file?

**Comment by bradennapier** [comment]
Interesting - I actually do see that in dev tools it is saying "Grammars Reloaded"

**Comment by bradennapier** [comment]
yeah ill add it to github.. .one moment thanks again!

**Comment by bradennapier** [comment]
Hmm one moment let me try something.  Does the package.json matter?  I had copied it from another language but never changed the package.json.  The language shows as language-dashtcl in atom packages though.

**Comment by bradennapier** [comment]
Boom! just like that it worked!

**Comment by bradennapier** [comment]
Thanks!  Perhaps some info in the docs on setup ?

**Comment by bradennapier** [comment]
Wow... its like i was in the dark ages before!  Speeding me up by at least 80% ! thanks! awesome!

**Comment by ldez** [comment]
I am very happy if I can speed up your work. It's a great reward for me.

**Comment by bradennapier** [comment]
This needs to be native in atom ....

**Comment by aleclarson** [comment]
I've realized you need to open the `language-*` package's root directory as a project in the tree view before things start working. Before, I just opened the `.cson` grammar file alone. I don't think this is documented anywhere?
