### ISSUE TITLE
Watch all grammar editors + other improvements

### ISSUE THREAD

**Issue by aleclarson** [ldez/atom-grammar-live-reload#3]
Hello, Ludovic!

In [**this commit**](https://github.com/aleclarson/atom-grammar-live-reload/commit/074b3d4d553ddf37bca1cade3f064daf193ca483), I've made several improvements to this package.

### Features
  - Watch *all* grammar editors for changes (when in dev mode)

### Fixes
  - Only watch grammars/*.cson files (instead of all .cson files)
  - Only reload the affected grammar (instead of all projects with a `grammars` directory)
  - Properly unload grammar packages

### Other
  - Enable the package by default
  - Remove support for Atom < v1.11.0
  - Remove 'season' dependency (Atom provides it)
  - Simplify implementation

Let me know if you'd be interested in merging some (or all) of these changes into your version.

Cheers! 🍻

**Comment by ldez** [comment]
Hello, I'm interested in some of these changes.

Open a PR, I will review.

**Comment by aleclarson** [comment]
Before I send the PR over, what is your opinion on the following changes:

- Enable the package by default
- Remove support for Atom < v1.11.0

Those ones seem to be the most contentious.

I think <1.11.0 support is unnecessary, since grammar maintainers should be using more recent versions by now (v1.11.0 came out in October 2016).

Enabling the package by default makes it easier for users to get going without configuration, since it's no longer necessary to specify a `language-*` package name.

**Comment by ldez** [comment]
- Remove support for Atom < v1.11.0 :heavy_check_mark: 

For the rest I preferred to comment directly on a PR
